PythonDjango/belt_reviewer/apps/beltreviewer/urls.py
from django.conf.urls import url
from views import index, new, create, show, show_user

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^new/$', new, name='new'),
    url(r'^create/$', create, name='create'),
    url(r'^(?P<id>\d+)/$', show, name='show'),
    url(r'^users/(?P<id>\d+)/$', show_user, name='show_user'),
]

PythonDjango/belt_reviewer/apps/login_registration/urls.py
from django.conf.urls import url
from views import index, login, register, success, logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login$', login, name='login'),
    url(r'^register$', register, name='register'),
    url(r'^success$', success, name='success'),
    url(r'^logout$', logout, name='logout'),
]

PythonDjango/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_registration.urls', namespace='login_reg')),
    url(r'^', include('apps.beltreviewer.urls', namespace='reviewer')),   
]

PythonDjango/belt_reviewer/apps/beltreviewer/models.py
from __future__ import unicode_literals
from ..login_registration.models import User
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

class ReviewManager(models.Manager):
    def create_review(self, form_data, user_id):
        try:
            book = self.fetch_book(form_data)
            user = User.objects.get(id=user_id)
            new_review = Review.objects.create(content=form_data['content'], rating=form_data['rating'], user=user, book=book)
            return (True, new_review)
        except:
            return (False, ["There was a problem creating the review..."])

    def fetch_book(self, form_data):
        try:
            book = Book.objects.get(id=form_data['book_id'])
        except:
            author = self.fetch_author(form_data)
            book = Book.objects.create(title=form_data['new_book'], author=author)
        return book

    def fetch_author(self, form_data):
        try:
            author = Author.objects.get(id=form_data['author_id'])
        except:
            author = Author.objects.create(name=form_data['new_author'])
        return author

    def fetch_recent(self):
        return Review.objects.all().order_by('created_at')[:3]

class Review(models.Model):
    content = models.TextField()
    rating = models.IntegerField()
    user = models.ForeignKey('login_registration.User')
    book = models.ForeignKey('Book', default=1)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = ReviewManager()

PythonDjango/belt_reviewer/apps/login_registration/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Count
import bcrypt, re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    def validateReg(self, request):
        errors = self.validate_inputs(request)

        if len(errors) > 0:
            return (False, errors)

        # No errors, time to hash the password
        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

        # pw is hashed, time to create new user
        user = self.create(name = request.POST['name'], alias=request.POST['alias'], email=request.POST['email'], pw_hash=pw_hash)

        return (True, user)

    def validateLogin(self, request):
        try:
            user = User.objects.get(email=request.POST['email'])
            # The email matched a record in the database, now test passwords
            password = request.POST['password'].encode()
            if bcrypt.hashpw(password, user.pw_hash.encode()):
                return (True, user)

        except ObjectDoesNotExist:
            pass

        return (False, ["Email/password don't match."])

    def validate_inputs(self, request):
        errors = []
        if len(request.POST['name']) < 2 or len(request.POST['alias']) < 2:
            errors.append("Please include a name or alias longer than two characters.")
        if not EMAIL_REGEX.match(request.POST['email']):
            errors.append("Please include a valid email.")
        if len(request.POST['password']) < 8 or request.POST['password'] != request.POST['confirm_pw']:
            errors.append("Passwords must match and be at least 8 characters.")

        return errors

    def fetch_user_info(self, id):
        return self.filter(id=id).annotate(total_reviews=Count('review'))[0]

class User(models.Model):
    name = models.CharField(max_length=100)
    alias= models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    pw_hash = models.CharField(max_length=255)

    objects = UserManager()

PythonDjango/belt_reviewer/apps/beltreviewer/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from models import Book, Author, Review
from ..login_registration.views import print_messages
from ..login_registration.models import User

# Create your views here.
from django.template import Library
register = Library()

def check_logged_in(request):
    return 'user' in request.session

def index(request):
    if not check_logged_in(request):
        return redirect(reverse('login_reg:index'))

    context = {
        'reviews': Review.objects.fetch_recent(),
        'books': Book.objects.all()
    }

    return render(request, 'beltreviewer/index.html', context)

def new(request):
    if not check_logged_in(request):
        return redirect(reverse('login_reg:index'))

    result = Review.objects.create_review(request.POST, request.session['user']['id'])

    if result[0] == True:
        return redirect(reverse('reviewer:show', kwargs={'id': result[1].book.id}))
    else:
        print_messages(request, result[1])
        return redirect(reverse('reviewer:new'))

def create(request):
    if not check_logged_in(request):
        return redirect(reverse('users:index'))

    result = Review.objects.create_review(request.POST, request.session['user']['id'])

    if result[0] == True:
        return redirect(reverse('reviews:show', kwargs={'id': result[1].book.id }))
    else:
        print_messages(request, result[1])
        return redirect(reverse('reviews:new'))

@register.filter
def show(request, id):
    if not check_logged_in(request):
        return redirect(reverse('login_reg:index'))

    book = Book.objects.get(id=id)
    return render(request, 'beltreviewer/show.html', { 'book': book })

@register.filter
def show_user(request, id):
    if not check_logged_in(request):
        return redirect(reverse('login_reg:index'))

    user = User.objects.fetch_user_info(id)
    return render(request, 'beltreviewer/show_user.html', { 'user': user })

PythonDjango/belt_reviewer/apps/login_registration/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from models import User

# Create your views here.
def index(request):
    return render(request, 'login_registration/index.html')

def login(request):
    result = User.objects.validateLogin(request)

    if result[0] == False:
        print_messages(request, result[1])
        return redirect(reverse('login_reg:index'))

    return log_user_in(request, result[1])

def register(request):
    result = User.objects.validateReg(request)

    if result[0] == False:
        print_messages(request, result[1])
        return redirect(reverse('login_reg:index'))

    return log_user_in(request, result[1])

def success(request):
    if not 'user' in request.session:
        return redirect(reverse('login_reg:index'))

    """
    For this app, success means allowing the user into book reviews
    """
    return redirect(reverse('reviewer:index'))

def print_messages(request, message_list):
    for message in message_list:
        messages.add_message(request, messages.INFO, message)

def log_user_in(request, user):
    request.session['user'] = {
        'id' : user.id,
        'name' : user.name,
        'alias' : user.alias,
        'email' : user.email,
    }
    return redirect(reverse('login_reg:success'))

def logout(request):
    request.session.pop('user')
    return redirect(reverse('login_reg:index'))

PythonDjango/belt_reviewer/apps/beltreviewer/templates/beltreviewer/index.html
{% load staticfiles %}
{% load range_maker %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Book Reviews</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <h2>Welcome {{ request.session.user.name }}</h2>
        <nav>
            <a href="{% url 'reviewer:new' %}">Add Book and Review</a>
            <a href="{% url 'login_reg:logout' %}">Logout</a>
        </nav>
    </header>
    <h1>Recent book reviews:</h1>
    <div class="recent">
        {% for review in reviews %}
        <div class="review">
            <h4><a href="{% url 'reviewer:show' id=review.book.id %}">{{review.book.title}}</a></h4>
            <h5>Rating</h5>
            {% for i in review.rating|range_maker %}
            <img class="star" src="{% static 'img/star.gif' %}" alt="star">
            {% endfor %}
            <p>{{review.user.name}} says: {{review.content}}</p>
            <p>Posted on {{review.created_at}}</p>
        </div>
        {% endfor %}
    </div>
    <div class="other-books">
        <h1>Other Books with Reviews</h1>
        {% for book in books %}
        <p><a href="{% url 'reviewer:show' id=book.id %}">{{book.title}}</a></p>
        {% endfor %}
    </div>
</body>
</html>

PythonDjango/belt_reviewer/apps/beltreviewer/templates/beltreviewer/new.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Book Reviews</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'reviewer:index' %}">Home</a>
            <a href="{% url 'login_reg:logout' %}">Logout</a>
        </nav>
    </header>
    <h1>Add a New Book Title or Review:</h1>
    <form action="{% url 'reviewer:create' %}" method="post">
        <% csrf_token %}
        Book Title:
        <select name="book_id">
            <option value="None">Book Title</option>
            {% for book in books %}
            <option value="{{book.id}}">{{book.title}}</option>
            {% endfor %}
        </select>
        <p>Or add a new book:</p>
        <input type="text" name="new_book" placeholder="Book Title">
        Author:
        <select name="author_id">
            <option value="None">Author Name</option>
            {% for author in authors %}
            <option value="{{author.id}}">{{author.name}}</option>
            {% endfor %}
        </select>
        <p>Or add a new author:</p>
        <input type="text" name="new_author" placeholder="Author Name">
        <h2>Review:</h2>
        <textarea name="content" rows="8" cols="40"></textarea>
        <h2>Rating:</h2>
        <select name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
        </select>
        <input type="submit" value="Add Book and Review">
    </form>
</body>
</html>

PythonDjango/belt_reviewer/apps/beltreviewer/templates/beltreviewer/show.html
{% load staticfiles %}
{% load range_maker %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Book Reviews</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'reviewer:index' %}">Home</a>
            <a href="{% url 'login_reg:logout' %}">Logout</a>
        </nav>
    </header>
    <h1>{{book.title}}</h1>
    <p>Author: {{book.author.name}}</p>

    <h1>Reviews</h1>
    <div class="recent">
        {% for review in book.review_set.all %}
        <div class="review">
            <h4>Rating</h4>
            {% for i in review.rating|range_maker %}
            <img class="star" src="{% static 'img/star.gif' %}" alt="star">
            {% endfor %}
            <p><a href="{% url 'reviewer:show_user' id_review.user.id %}">{{review.user.name}}</a> says: {{review.content}}</p>
            <p>Posted on {{review.created_at}}</p>
        </div>
        {% endfor %}
    </div>

    <div class="new-review">
        <h1>Add a Review</h1>
        <form action="{% url 'reviewer:create' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{book.id}}">
            <textarea name="content" rows="8" cols="40"></textarea>
            <p>Rating:</p>
            <select name="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
            </select>
            <input type="submit" value="Submit Review">
        </form>
    </div>
</body>
</html>

PythonDjango/belt_reviewer/apps/beltreviewer/templates/beltreviewer/show_user.html
{% load staticfiles %}
{% load range_maker %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Book Reviews</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'reviewer:index' %}">Home</a>
            <a href="{% url 'login_reg:logout' %}">Logout</a>
        </nav>
    </header>
    <h1>User Alias: {{user.alias}} </h1>
    <h2>Name: {{user.name}}</h2>
    <h2>Email: {{user.email}}</h2>
    <h2>Total Reviews: {{user.total_reviews}}</h2>
    <h2>Posted Reviews on the following books:</h2>
    {% for review in user.review_set.all %}
    <p><a href="{% url 'reviewer:show' id=review.book.id %}">{{review.book.title}}</a></p>
    {% endfor %}
</body>
</html>